
namespace PresentationLayer
{
    partial class Registration
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Registration));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel2 = new System.Windows.Forms.Panel();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bunifuTextBoxPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuTextBoxPhone = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuTextBoxAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuTextBoxNameS = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuTextBoxEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuTextBoxCity = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuTextBoxUserName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuButtonRegistration = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel2
            // 
            this.panel2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(72)))), ((int)(((byte)(92)))));
            this.panel2.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel2.Location = new System.Drawing.Point(0, 0);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(800, 203);
            this.panel2.TabIndex = 4;
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.White;
            this.panel1.Controls.Add(this.bunifuTextBoxPassword);
            this.panel1.Controls.Add(this.bunifuTextBoxPhone);
            this.panel1.Controls.Add(this.bunifuTextBoxAddress);
            this.panel1.Controls.Add(this.bunifuTextBoxNameS);
            this.panel1.Controls.Add(this.bunifuTextBoxEmail);
            this.panel1.Controls.Add(this.bunifuTextBoxCity);
            this.panel1.Controls.Add(this.bunifuTextBoxUserName);
            this.panel1.Controls.Add(this.bunifuButtonRegistration);
            this.panel1.Location = new System.Drawing.Point(71, 26);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(659, 531);
            this.panel1.TabIndex = 5;
            // 
            // bunifuTextBoxPassword
            // 
            this.bunifuTextBoxPassword.AcceptsReturn = false;
            this.bunifuTextBoxPassword.AcceptsTab = false;
            this.bunifuTextBoxPassword.AnimationSpeed = 200;
            this.bunifuTextBoxPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxPassword.BackColor = System.Drawing.Color.White;
            this.bunifuTextBoxPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxPassword.BackgroundImage")));
            this.bunifuTextBoxPassword.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxPassword.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxPassword.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxPassword.BorderRadius = 1;
            this.bunifuTextBoxPassword.BorderThickness = 1;
            this.bunifuTextBoxPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBoxPassword.DefaultText = "";
            this.bunifuTextBoxPassword.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxPassword.HideSelection = true;
            this.bunifuTextBoxPassword.IconLeft = null;
            this.bunifuTextBoxPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxPassword.IconPadding = 10;
            this.bunifuTextBoxPassword.IconRight = null;
            this.bunifuTextBoxPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxPassword.Lines = new string[0];
            this.bunifuTextBoxPassword.Location = new System.Drawing.Point(199, 382);
            this.bunifuTextBoxPassword.MaxLength = 32767;
            this.bunifuTextBoxPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxPassword.Modified = false;
            this.bunifuTextBoxPassword.Multiline = false;
            this.bunifuTextBoxPassword.Name = "bunifuTextBoxPassword";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxPassword.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxPassword.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxPassword.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxPassword.OnIdleState = stateProperties4;
            this.bunifuTextBoxPassword.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBoxPassword.PasswordChar = '*';
            this.bunifuTextBoxPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBoxPassword.PlaceholderText = "Password";
            this.bunifuTextBoxPassword.ReadOnly = false;
            this.bunifuTextBoxPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxPassword.SelectedText = "";
            this.bunifuTextBoxPassword.SelectionLength = 0;
            this.bunifuTextBoxPassword.SelectionStart = 0;
            this.bunifuTextBoxPassword.ShortcutsEnabled = true;
            this.bunifuTextBoxPassword.Size = new System.Drawing.Size(260, 41);
            this.bunifuTextBoxPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.bunifuTextBoxPassword.TabIndex = 32;
            this.bunifuTextBoxPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxPassword.TextMarginBottom = 0;
            this.bunifuTextBoxPassword.TextMarginLeft = 3;
            this.bunifuTextBoxPassword.TextMarginTop = 0;
            this.bunifuTextBoxPassword.TextPlaceholder = "Password";
            this.bunifuTextBoxPassword.UseSystemPasswordChar = false;
            this.bunifuTextBoxPassword.WordWrap = true;
            // 
            // bunifuTextBoxPhone
            // 
            this.bunifuTextBoxPhone.AcceptsReturn = false;
            this.bunifuTextBoxPhone.AcceptsTab = false;
            this.bunifuTextBoxPhone.AnimationSpeed = 200;
            this.bunifuTextBoxPhone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxPhone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxPhone.BackColor = System.Drawing.Color.White;
            this.bunifuTextBoxPhone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxPhone.BackgroundImage")));
            this.bunifuTextBoxPhone.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxPhone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxPhone.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxPhone.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxPhone.BorderRadius = 1;
            this.bunifuTextBoxPhone.BorderThickness = 1;
            this.bunifuTextBoxPhone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxPhone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxPhone.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBoxPhone.DefaultText = "";
            this.bunifuTextBoxPhone.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxPhone.HideSelection = true;
            this.bunifuTextBoxPhone.IconLeft = null;
            this.bunifuTextBoxPhone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxPhone.IconPadding = 10;
            this.bunifuTextBoxPhone.IconRight = null;
            this.bunifuTextBoxPhone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxPhone.Lines = new string[0];
            this.bunifuTextBoxPhone.Location = new System.Drawing.Point(199, 323);
            this.bunifuTextBoxPhone.MaxLength = 32767;
            this.bunifuTextBoxPhone.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxPhone.Modified = false;
            this.bunifuTextBoxPhone.Multiline = false;
            this.bunifuTextBoxPhone.Name = "bunifuTextBoxPhone";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxPhone.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxPhone.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxPhone.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxPhone.OnIdleState = stateProperties8;
            this.bunifuTextBoxPhone.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBoxPhone.PasswordChar = '\0';
            this.bunifuTextBoxPhone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBoxPhone.PlaceholderText = "Phone Number";
            this.bunifuTextBoxPhone.ReadOnly = false;
            this.bunifuTextBoxPhone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxPhone.SelectedText = "";
            this.bunifuTextBoxPhone.SelectionLength = 0;
            this.bunifuTextBoxPhone.SelectionStart = 0;
            this.bunifuTextBoxPhone.ShortcutsEnabled = true;
            this.bunifuTextBoxPhone.Size = new System.Drawing.Size(260, 41);
            this.bunifuTextBoxPhone.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.bunifuTextBoxPhone.TabIndex = 31;
            this.bunifuTextBoxPhone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxPhone.TextMarginBottom = 0;
            this.bunifuTextBoxPhone.TextMarginLeft = 3;
            this.bunifuTextBoxPhone.TextMarginTop = 0;
            this.bunifuTextBoxPhone.TextPlaceholder = "Phone Number";
            this.bunifuTextBoxPhone.UseSystemPasswordChar = false;
            this.bunifuTextBoxPhone.WordWrap = true;
            // 
            // bunifuTextBoxAddress
            // 
            this.bunifuTextBoxAddress.AcceptsReturn = false;
            this.bunifuTextBoxAddress.AcceptsTab = false;
            this.bunifuTextBoxAddress.AnimationSpeed = 200;
            this.bunifuTextBoxAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxAddress.BackColor = System.Drawing.Color.White;
            this.bunifuTextBoxAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxAddress.BackgroundImage")));
            this.bunifuTextBoxAddress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxAddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxAddress.BorderRadius = 1;
            this.bunifuTextBoxAddress.BorderThickness = 1;
            this.bunifuTextBoxAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxAddress.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBoxAddress.DefaultText = "";
            this.bunifuTextBoxAddress.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxAddress.HideSelection = true;
            this.bunifuTextBoxAddress.IconLeft = null;
            this.bunifuTextBoxAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxAddress.IconPadding = 10;
            this.bunifuTextBoxAddress.IconRight = null;
            this.bunifuTextBoxAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxAddress.Lines = new string[0];
            this.bunifuTextBoxAddress.Location = new System.Drawing.Point(199, 264);
            this.bunifuTextBoxAddress.MaxLength = 32767;
            this.bunifuTextBoxAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxAddress.Modified = false;
            this.bunifuTextBoxAddress.Multiline = false;
            this.bunifuTextBoxAddress.Name = "bunifuTextBoxAddress";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxAddress.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxAddress.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxAddress.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxAddress.OnIdleState = stateProperties12;
            this.bunifuTextBoxAddress.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBoxAddress.PasswordChar = '\0';
            this.bunifuTextBoxAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBoxAddress.PlaceholderText = "Address";
            this.bunifuTextBoxAddress.ReadOnly = false;
            this.bunifuTextBoxAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxAddress.SelectedText = "";
            this.bunifuTextBoxAddress.SelectionLength = 0;
            this.bunifuTextBoxAddress.SelectionStart = 0;
            this.bunifuTextBoxAddress.ShortcutsEnabled = true;
            this.bunifuTextBoxAddress.Size = new System.Drawing.Size(260, 41);
            this.bunifuTextBoxAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.bunifuTextBoxAddress.TabIndex = 30;
            this.bunifuTextBoxAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxAddress.TextMarginBottom = 0;
            this.bunifuTextBoxAddress.TextMarginLeft = 3;
            this.bunifuTextBoxAddress.TextMarginTop = 0;
            this.bunifuTextBoxAddress.TextPlaceholder = "Address";
            this.bunifuTextBoxAddress.UseSystemPasswordChar = false;
            this.bunifuTextBoxAddress.WordWrap = true;
            // 
            // bunifuTextBoxNameS
            // 
            this.bunifuTextBoxNameS.AcceptsReturn = false;
            this.bunifuTextBoxNameS.AcceptsTab = false;
            this.bunifuTextBoxNameS.AnimationSpeed = 200;
            this.bunifuTextBoxNameS.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxNameS.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxNameS.BackColor = System.Drawing.Color.White;
            this.bunifuTextBoxNameS.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxNameS.BackgroundImage")));
            this.bunifuTextBoxNameS.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxNameS.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxNameS.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxNameS.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxNameS.BorderRadius = 1;
            this.bunifuTextBoxNameS.BorderThickness = 1;
            this.bunifuTextBoxNameS.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxNameS.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxNameS.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBoxNameS.DefaultText = "";
            this.bunifuTextBoxNameS.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxNameS.HideSelection = true;
            this.bunifuTextBoxNameS.IconLeft = null;
            this.bunifuTextBoxNameS.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxNameS.IconPadding = 10;
            this.bunifuTextBoxNameS.IconRight = null;
            this.bunifuTextBoxNameS.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxNameS.Lines = new string[0];
            this.bunifuTextBoxNameS.Location = new System.Drawing.Point(199, 78);
            this.bunifuTextBoxNameS.MaxLength = 32767;
            this.bunifuTextBoxNameS.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxNameS.Modified = false;
            this.bunifuTextBoxNameS.Multiline = false;
            this.bunifuTextBoxNameS.Name = "bunifuTextBoxNameS";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxNameS.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxNameS.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxNameS.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxNameS.OnIdleState = stateProperties16;
            this.bunifuTextBoxNameS.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBoxNameS.PasswordChar = '\0';
            this.bunifuTextBoxNameS.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBoxNameS.PlaceholderText = "Name";
            this.bunifuTextBoxNameS.ReadOnly = false;
            this.bunifuTextBoxNameS.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxNameS.SelectedText = "";
            this.bunifuTextBoxNameS.SelectionLength = 0;
            this.bunifuTextBoxNameS.SelectionStart = 0;
            this.bunifuTextBoxNameS.ShortcutsEnabled = true;
            this.bunifuTextBoxNameS.Size = new System.Drawing.Size(260, 41);
            this.bunifuTextBoxNameS.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.bunifuTextBoxNameS.TabIndex = 29;
            this.bunifuTextBoxNameS.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxNameS.TextMarginBottom = 0;
            this.bunifuTextBoxNameS.TextMarginLeft = 3;
            this.bunifuTextBoxNameS.TextMarginTop = 0;
            this.bunifuTextBoxNameS.TextPlaceholder = "Name";
            this.bunifuTextBoxNameS.UseSystemPasswordChar = false;
            this.bunifuTextBoxNameS.WordWrap = true;
            // 
            // bunifuTextBoxEmail
            // 
            this.bunifuTextBoxEmail.AcceptsReturn = false;
            this.bunifuTextBoxEmail.AcceptsTab = false;
            this.bunifuTextBoxEmail.AnimationSpeed = 200;
            this.bunifuTextBoxEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxEmail.BackColor = System.Drawing.Color.White;
            this.bunifuTextBoxEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxEmail.BackgroundImage")));
            this.bunifuTextBoxEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxEmail.BorderRadius = 1;
            this.bunifuTextBoxEmail.BorderThickness = 1;
            this.bunifuTextBoxEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBoxEmail.DefaultText = "";
            this.bunifuTextBoxEmail.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxEmail.HideSelection = true;
            this.bunifuTextBoxEmail.IconLeft = null;
            this.bunifuTextBoxEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxEmail.IconPadding = 10;
            this.bunifuTextBoxEmail.IconRight = null;
            this.bunifuTextBoxEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxEmail.Lines = new string[0];
            this.bunifuTextBoxEmail.Location = new System.Drawing.Point(199, 138);
            this.bunifuTextBoxEmail.MaxLength = 32767;
            this.bunifuTextBoxEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxEmail.Modified = false;
            this.bunifuTextBoxEmail.Multiline = false;
            this.bunifuTextBoxEmail.Name = "bunifuTextBoxEmail";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxEmail.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxEmail.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxEmail.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxEmail.OnIdleState = stateProperties20;
            this.bunifuTextBoxEmail.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBoxEmail.PasswordChar = '\0';
            this.bunifuTextBoxEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBoxEmail.PlaceholderText = "Email";
            this.bunifuTextBoxEmail.ReadOnly = false;
            this.bunifuTextBoxEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxEmail.SelectedText = "";
            this.bunifuTextBoxEmail.SelectionLength = 0;
            this.bunifuTextBoxEmail.SelectionStart = 0;
            this.bunifuTextBoxEmail.ShortcutsEnabled = true;
            this.bunifuTextBoxEmail.Size = new System.Drawing.Size(260, 41);
            this.bunifuTextBoxEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.bunifuTextBoxEmail.TabIndex = 28;
            this.bunifuTextBoxEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxEmail.TextMarginBottom = 0;
            this.bunifuTextBoxEmail.TextMarginLeft = 3;
            this.bunifuTextBoxEmail.TextMarginTop = 0;
            this.bunifuTextBoxEmail.TextPlaceholder = "Email";
            this.bunifuTextBoxEmail.UseSystemPasswordChar = false;
            this.bunifuTextBoxEmail.WordWrap = true;
            // 
            // bunifuTextBoxCity
            // 
            this.bunifuTextBoxCity.AcceptsReturn = false;
            this.bunifuTextBoxCity.AcceptsTab = false;
            this.bunifuTextBoxCity.AnimationSpeed = 200;
            this.bunifuTextBoxCity.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxCity.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxCity.BackColor = System.Drawing.Color.White;
            this.bunifuTextBoxCity.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxCity.BackgroundImage")));
            this.bunifuTextBoxCity.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxCity.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxCity.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxCity.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxCity.BorderRadius = 1;
            this.bunifuTextBoxCity.BorderThickness = 1;
            this.bunifuTextBoxCity.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxCity.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxCity.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBoxCity.DefaultText = "";
            this.bunifuTextBoxCity.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxCity.HideSelection = true;
            this.bunifuTextBoxCity.IconLeft = null;
            this.bunifuTextBoxCity.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxCity.IconPadding = 10;
            this.bunifuTextBoxCity.IconRight = null;
            this.bunifuTextBoxCity.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxCity.Lines = new string[0];
            this.bunifuTextBoxCity.Location = new System.Drawing.Point(199, 203);
            this.bunifuTextBoxCity.MaxLength = 32767;
            this.bunifuTextBoxCity.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxCity.Modified = false;
            this.bunifuTextBoxCity.Multiline = false;
            this.bunifuTextBoxCity.Name = "bunifuTextBoxCity";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxCity.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxCity.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxCity.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxCity.OnIdleState = stateProperties24;
            this.bunifuTextBoxCity.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBoxCity.PasswordChar = '\0';
            this.bunifuTextBoxCity.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBoxCity.PlaceholderText = "City";
            this.bunifuTextBoxCity.ReadOnly = false;
            this.bunifuTextBoxCity.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxCity.SelectedText = "";
            this.bunifuTextBoxCity.SelectionLength = 0;
            this.bunifuTextBoxCity.SelectionStart = 0;
            this.bunifuTextBoxCity.ShortcutsEnabled = true;
            this.bunifuTextBoxCity.Size = new System.Drawing.Size(260, 41);
            this.bunifuTextBoxCity.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.bunifuTextBoxCity.TabIndex = 27;
            this.bunifuTextBoxCity.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxCity.TextMarginBottom = 0;
            this.bunifuTextBoxCity.TextMarginLeft = 3;
            this.bunifuTextBoxCity.TextMarginTop = 0;
            this.bunifuTextBoxCity.TextPlaceholder = "City";
            this.bunifuTextBoxCity.UseSystemPasswordChar = false;
            this.bunifuTextBoxCity.WordWrap = true;
            // 
            // bunifuTextBoxUserName
            // 
            this.bunifuTextBoxUserName.AcceptsReturn = false;
            this.bunifuTextBoxUserName.AcceptsTab = false;
            this.bunifuTextBoxUserName.AnimationSpeed = 200;
            this.bunifuTextBoxUserName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBoxUserName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBoxUserName.BackColor = System.Drawing.Color.White;
            this.bunifuTextBoxUserName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBoxUserName.BackgroundImage")));
            this.bunifuTextBoxUserName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBoxUserName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBoxUserName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBoxUserName.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBoxUserName.BorderRadius = 1;
            this.bunifuTextBoxUserName.BorderThickness = 1;
            this.bunifuTextBoxUserName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBoxUserName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxUserName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBoxUserName.DefaultText = "";
            this.bunifuTextBoxUserName.FillColor = System.Drawing.Color.White;
            this.bunifuTextBoxUserName.HideSelection = true;
            this.bunifuTextBoxUserName.IconLeft = null;
            this.bunifuTextBoxUserName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxUserName.IconPadding = 10;
            this.bunifuTextBoxUserName.IconRight = null;
            this.bunifuTextBoxUserName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBoxUserName.Lines = new string[0];
            this.bunifuTextBoxUserName.Location = new System.Drawing.Point(199, 19);
            this.bunifuTextBoxUserName.MaxLength = 32767;
            this.bunifuTextBoxUserName.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBoxUserName.Modified = false;
            this.bunifuTextBoxUserName.Multiline = false;
            this.bunifuTextBoxUserName.Name = "bunifuTextBoxUserName";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxUserName.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBoxUserName.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxUserName.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBoxUserName.OnIdleState = stateProperties28;
            this.bunifuTextBoxUserName.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBoxUserName.PasswordChar = '\0';
            this.bunifuTextBoxUserName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bunifuTextBoxUserName.PlaceholderText = "Username";
            this.bunifuTextBoxUserName.ReadOnly = false;
            this.bunifuTextBoxUserName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBoxUserName.SelectedText = "";
            this.bunifuTextBoxUserName.SelectionLength = 0;
            this.bunifuTextBoxUserName.SelectionStart = 0;
            this.bunifuTextBoxUserName.ShortcutsEnabled = true;
            this.bunifuTextBoxUserName.Size = new System.Drawing.Size(260, 41);
            this.bunifuTextBoxUserName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.bunifuTextBoxUserName.TabIndex = 26;
            this.bunifuTextBoxUserName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBoxUserName.TextMarginBottom = 0;
            this.bunifuTextBoxUserName.TextMarginLeft = 3;
            this.bunifuTextBoxUserName.TextMarginTop = 0;
            this.bunifuTextBoxUserName.TextPlaceholder = "Username";
            this.bunifuTextBoxUserName.UseSystemPasswordChar = false;
            this.bunifuTextBoxUserName.WordWrap = true;
            // 
            // bunifuButtonRegistration
            // 
            this.bunifuButtonRegistration.AllowAnimations = true;
            this.bunifuButtonRegistration.AllowMouseEffects = true;
            this.bunifuButtonRegistration.AllowToggling = false;
            this.bunifuButtonRegistration.AnimationSpeed = 200;
            this.bunifuButtonRegistration.AutoGenerateColors = false;
            this.bunifuButtonRegistration.AutoRoundBorders = false;
            this.bunifuButtonRegistration.AutoSizeLeftIcon = true;
            this.bunifuButtonRegistration.AutoSizeRightIcon = true;
            this.bunifuButtonRegistration.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButtonRegistration.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(72)))), ((int)(((byte)(92)))));
            this.bunifuButtonRegistration.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButtonRegistration.BackgroundImage")));
            this.bunifuButtonRegistration.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonRegistration.ButtonText = "REGISTRATION";
            this.bunifuButtonRegistration.ButtonTextMarginLeft = 0;
            this.bunifuButtonRegistration.ColorContrastOnClick = 45;
            this.bunifuButtonRegistration.ColorContrastOnHover = 45;
            this.bunifuButtonRegistration.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButtonRegistration.CustomizableEdges = borderEdges1;
            this.bunifuButtonRegistration.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButtonRegistration.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(216)))), ((int)(((byte)(216)))));
            this.bunifuButtonRegistration.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonRegistration.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonRegistration.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButtonRegistration.Font = new System.Drawing.Font("Segoe UI Semibold", 10.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButtonRegistration.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonRegistration.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButtonRegistration.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonRegistration.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButtonRegistration.IconMarginLeft = 11;
            this.bunifuButtonRegistration.IconPadding = 10;
            this.bunifuButtonRegistration.IconRightAlign = System.Drawing.ContentAlignment.BottomLeft;
            this.bunifuButtonRegistration.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButtonRegistration.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButtonRegistration.IconSize = 25;
            this.bunifuButtonRegistration.IdleBorderColor = System.Drawing.SystemColors.ActiveBorder;
            this.bunifuButtonRegistration.IdleBorderRadius = 1;
            this.bunifuButtonRegistration.IdleBorderThickness = 1;
            this.bunifuButtonRegistration.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(72)))), ((int)(((byte)(92)))));
            this.bunifuButtonRegistration.IdleIconLeftImage = null;
            this.bunifuButtonRegistration.IdleIconRightImage = null;
            this.bunifuButtonRegistration.IndicateFocus = false;
            this.bunifuButtonRegistration.Location = new System.Drawing.Point(228, 464);
            this.bunifuButtonRegistration.Name = "bunifuButtonRegistration";
            this.bunifuButtonRegistration.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(178)))), ((int)(((byte)(216)))), ((int)(((byte)(216)))));
            this.bunifuButtonRegistration.OnDisabledState.BorderRadius = 1;
            this.bunifuButtonRegistration.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonRegistration.OnDisabledState.BorderThickness = 1;
            this.bunifuButtonRegistration.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButtonRegistration.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButtonRegistration.OnDisabledState.IconLeftImage = null;
            this.bunifuButtonRegistration.OnDisabledState.IconRightImage = null;
            this.bunifuButtonRegistration.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(131)))), ((int)(((byte)(103)))), ((int)(((byte)(123)))));
            this.bunifuButtonRegistration.onHoverState.BorderRadius = 1;
            this.bunifuButtonRegistration.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonRegistration.onHoverState.BorderThickness = 1;
            this.bunifuButtonRegistration.onHoverState.FillColor = System.Drawing.Color.Silver;
            this.bunifuButtonRegistration.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonRegistration.onHoverState.IconLeftImage = null;
            this.bunifuButtonRegistration.onHoverState.IconRightImage = null;
            this.bunifuButtonRegistration.OnIdleState.BorderColor = System.Drawing.SystemColors.ActiveBorder;
            this.bunifuButtonRegistration.OnIdleState.BorderRadius = 1;
            this.bunifuButtonRegistration.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonRegistration.OnIdleState.BorderThickness = 1;
            this.bunifuButtonRegistration.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(72)))), ((int)(((byte)(92)))));
            this.bunifuButtonRegistration.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonRegistration.OnIdleState.IconLeftImage = null;
            this.bunifuButtonRegistration.OnIdleState.IconRightImage = null;
            this.bunifuButtonRegistration.OnPressedState.BorderColor = System.Drawing.Color.Gray;
            this.bunifuButtonRegistration.OnPressedState.BorderRadius = 1;
            this.bunifuButtonRegistration.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButtonRegistration.OnPressedState.BorderThickness = 1;
            this.bunifuButtonRegistration.OnPressedState.FillColor = System.Drawing.Color.Gray;
            this.bunifuButtonRegistration.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButtonRegistration.OnPressedState.IconLeftImage = null;
            this.bunifuButtonRegistration.OnPressedState.IconRightImage = null;
            this.bunifuButtonRegistration.Size = new System.Drawing.Size(197, 47);
            this.bunifuButtonRegistration.TabIndex = 25;
            this.bunifuButtonRegistration.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButtonRegistration.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButtonRegistration.TextMarginLeft = 0;
            this.bunifuButtonRegistration.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButtonRegistration.UseDefaultRadiusAndThickness = true;
            this.bunifuButtonRegistration.Click += new System.EventHandler(this.bunifuButtonRegistration_Click);
            // 
            // Registration
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 583);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.panel2);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Name = "Registration";
            this.Text = "Registration";
            this.panel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxPassword;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxPhone;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxAddress;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxNameS;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxEmail;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxCity;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBoxUserName;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButtonRegistration;
    }
}